repos:
  - repo: local
    hooks:
      - id: cargo-fmt
        name: cargo fmt
        entry: cargo fmt --all
        language: system
        pass_filenames: false
        stages: [pre-commit]

      - id: ruff
        name: ruff
        entry: ruff format
        language: system
        types_or: [python, pyi]
        stages: [pre-commit]
